SET NAMES utf8mb4;
CREATE TABLE usuarios (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, nome VARCHAR(100) NOT NULL, email VARCHAR(150) NOT NULL UNIQUE,
 senha_hash VARCHAR(255) NOT NULL, perfil ENUM('cliente','barbeiro','admin') NOT NULL DEFAULT 'cliente',
 ativo TINYINT(1) NOT NULL DEFAULT 1, force_reset TINYINT(1) NOT NULL DEFAULT 0, criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
CREATE TABLE tokens_senha (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, usuario_id INT UNSIGNED NOT NULL, token VARCHAR(64) NOT NULL UNIQUE, expira_em DATETIME NOT NULL, usado TINYINT(1) NOT NULL DEFAULT 0, criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE categorias (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, nome VARCHAR(60) NOT NULL, descricao VARCHAR(255), ordem TINYINT UNSIGNED NOT NULL DEFAULT 0, ativo TINYINT(1) NOT NULL DEFAULT 1) ENGINE=InnoDB;
CREATE TABLE servicos (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, categoria_id INT UNSIGNED NOT NULL, nome VARCHAR(100) NOT NULL, descricao TEXT, preco DECIMAL(8,2) NOT NULL, duracao_min SMALLINT UNSIGNED NOT NULL, ativo TINYINT(1) NOT NULL DEFAULT 1, criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(categoria_id) REFERENCES categorias(id)) ENGINE=InnoDB;
CREATE TABLE servico_fotos (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, servico_id INT UNSIGNED NOT NULL, foto_path VARCHAR(255) NOT NULL, ordem TINYINT UNSIGNED NOT NULL DEFAULT 0, FOREIGN KEY(servico_id) REFERENCES servicos(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE combos (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, nome VARCHAR(100) NOT NULL, descricao TEXT, preco DECIMAL(8,2) NOT NULL, duracao_min SMALLINT UNSIGNED NOT NULL, ativo TINYINT(1) NOT NULL DEFAULT 1, criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE combo_servicos (combo_id INT UNSIGNED NOT NULL, servico_id INT UNSIGNED NOT NULL, PRIMARY KEY(combo_id,servico_id), FOREIGN KEY(combo_id) REFERENCES combos(id) ON DELETE CASCADE, FOREIGN KEY(servico_id) REFERENCES servicos(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE barbeiro_servicos (barbeiro_id INT UNSIGNED NOT NULL, servico_id INT UNSIGNED NOT NULL, PRIMARY KEY(barbeiro_id,servico_id), FOREIGN KEY(barbeiro_id) REFERENCES usuarios(id) ON DELETE CASCADE, FOREIGN KEY(servico_id) REFERENCES servicos(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE barbeiro_combos (barbeiro_id INT UNSIGNED NOT NULL, combo_id INT UNSIGNED NOT NULL, PRIMARY KEY(barbeiro_id,combo_id), FOREIGN KEY(barbeiro_id) REFERENCES usuarios(id) ON DELETE CASCADE, FOREIGN KEY(combo_id) REFERENCES combos(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE carga_horaria (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, barbeiro_id INT UNSIGNED NOT NULL, dia_semana TINYINT UNSIGNED NOT NULL, hora_inicio TIME NOT NULL, hora_fim TIME NOT NULL, UNIQUE KEY uq_barbeiro_dia(barbeiro_id,dia_semana), FOREIGN KEY(barbeiro_id) REFERENCES usuarios(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE bloqueios (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, barbeiro_id INT UNSIGNED NOT NULL, data DATE NOT NULL, hora_inicio TIME NOT NULL, hora_fim TIME NOT NULL, FOREIGN KEY(barbeiro_id) REFERENCES usuarios(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE agendamentos (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, cliente_id INT UNSIGNED NOT NULL, barbeiro_id INT UNSIGNED NOT NULL, servico_id INT UNSIGNED NULL, combo_id INT UNSIGNED NULL, data_hora DATETIME NOT NULL, duracao_min SMALLINT UNSIGNED NOT NULL, preco DECIMAL(8,2) NOT NULL, status ENUM('pendente','confirmado','cancelado','nao_confirmado') NOT NULL DEFAULT 'pendente', token_confirm VARCHAR(64) NOT NULL UNIQUE, confirmado_em DATETIME NULL, cancelado_em DATETIME NULL, cancelado_por ENUM('cliente','barbeiro','admin') NULL, criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(cliente_id) REFERENCES usuarios(id), FOREIGN KEY(barbeiro_id) REFERENCES usuarios(id), FOREIGN KEY(servico_id) REFERENCES servicos(id), FOREIGN KEY(combo_id) REFERENCES combos(id), INDEX idx_agend_barbeiro_data(barbeiro_id,data_hora), INDEX idx_agend_cliente(cliente_id)) ENGINE=InnoDB;
CREATE TABLE portfolio (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, barbeiro_id INT UNSIGNED NOT NULL, servico_id INT UNSIGNED NULL, foto_path VARCHAR(255) NOT NULL, legenda VARCHAR(255), criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(barbeiro_id) REFERENCES usuarios(id) ON DELETE CASCADE, FOREIGN KEY(servico_id) REFERENCES servicos(id) ON DELETE SET NULL) ENGINE=InnoDB;
CREATE TABLE tickets (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, barbeiro_id INT UNSIGNED NOT NULL, nome VARCHAR(100) NOT NULL, descricao TEXT, categoria_id INT UNSIGNED NULL, preco DECIMAL(8,2), duracao_min SMALLINT UNSIGNED, status ENUM('pendente','aprovado','recusado') NOT NULL DEFAULT 'pendente', obs_admin TEXT, criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, resolvido_em DATETIME NULL, FOREIGN KEY(barbeiro_id) REFERENCES usuarios(id), FOREIGN KEY(categoria_id) REFERENCES categorias(id) ON DELETE SET NULL) ENGINE=InnoDB;
CREATE TABLE mensagens_rapidas (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, titulo VARCHAR(100) NOT NULL, corpo TEXT NOT NULL, ativo TINYINT(1) NOT NULL DEFAULT 1) ENGINE=InnoDB;
INSERT INTO usuarios(nome,email,senha_hash,perfil) VALUES ('Administrador','admin@navalha.com.br','$2y$12$Vr3/41h26Mvb9nerU/Rwiu9P/gWVYspd30jakmF6mh92gp5HJcdeS','admin');
INSERT INTO usuarios(nome,email,senha_hash,perfil) VALUES ('admTeste','teste@adm.com','$2y$12$N9Xcjdqf9k.AM7VFHtJ7xe34b7yge9ZqG5R0lYWAIaKGPPxGJ2kHO','admin');
INSERT INTO categorias(nome,descricao,ordem) VALUES ('Cabelo','Cortes clássicos e modernos',1),('Barba','Cuidados e acabamento',2),('Sobrancelha','Design preciso',3);
INSERT INTO servicos(categoria_id,nome,descricao,preco,duracao_min) VALUES (1,'Corte social','Acabamento na navalha e finalização com pomada.',40,45),(1,'Degradê','Fade baixo, médio ou alto com acabamento.',45,45),(2,'Barba completa','Desenho, aparagem e toalha quente.',30,45),(3,'Design de sobrancelha','Modelagem com pinça e navalha.',15,20);
INSERT INTO combos(nome,descricao,preco,duracao_min) VALUES ('Corte + Barba','Corte social ou degradê com barba completa.',65,90),('Visual completo','Corte, barba e sobrancelha.',75,110);
